### ISSUE TITLE
Can't access the SDOML data on the colab notebook

### ISSUE THREAD

**Issue by brash6** [spaceml-org/helionb-sdoml#9]
Hello, 

I would like to use the GCP api to perform ML tasks on the SDOML dataset but it seems that I can't access the data from the colab notebook. 
When I try to run this cell : 
```
# first, we create a group with the store data located on GCP.
root = zarr.group(store)
```

I get this error : 

`RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f0289b95ae0>)`

Is it an authentication issue ?

**Comment by PaulJWright** [comment]
The GCP bucket may be private now. Have you tried the AWS version? That should work fine

**Comment by brash6** [comment]
I have tried it and it works, thank you !
